### ISSUE TITLE
Constraints not find in UNL hierarchy

### ISSUE THREAD

**Issue by lancioni** [dikonov/Universal-Dictionary-of-Concepts#1]
While browsing the csv file I noticed that a number of UNL entries restrict the agent as a volitional_thing. While this is a very welcome piece of information, since it narrows the set of possible agents for a given verb (or other entry), the volitional_thing UW itself does not exist and it is not possible to find it in the UNLKB either.

The old UNL System manual did have a volitional_thing fifth level UW (see, e.g., http://web.archive.org/web/20031230075637/http://www.unlc.undl.org:80/unlsys/uw/uwmanv20.htm), but that does not seem to be represented anymore nowhere in the lexical databases. This way, a useful restriction is not practically enforceable.

One solution could be matching volitional_thing with a WordNet synset: perhaps causal_agent? I am not sure.

**Comment by dikonov** [comment]
This is a valid piece of criticism. In fact, there are other restrictions that point to missing UWs as well, because 1) completeness was not considered to be a requirement while making the initial set of UWs and 2) UWs, which are not derived directly from word senses, were discouraged. I shall add this UW soon.

I am working on a new set of UW - SUMO ontology bindings that should help to provide a much better set of icl relations (many of which are still not published) and and improve the connectedness of the UW semantic network.

Feel free to report other annoing gaps or make requests/contributions.

Viacheslav Dikonov

**Comment by dikonov** [comment]
I have checked the current git version of UNLDC and it does contain such UWs as

thing(icl>uw)
abstract_thing(icl>thing)
concrete_thing(icl>thing)
functional_thing(icl>thing)
living_thing(icl>thing)
_ volitional_thing(icl>thing) _
...

Please, check that you are looking at the latest version of the data. The xdxf version is hopelessly old and cannot be updated properly because of github limitations.

**Comment by lancioni** [comment]
Thank you for your answer: of course, such matters of design are typically set aside in the earliest stages of a project and become noticeable when it gets hard to correct them. In this specific case, I suspect the difficult thing would be to change the last item in a number of icl chains from thing to volitional_thing (otherwise, having a volitional_thing UW would be pretty useless).

Another thing that could be improved is having fully nonambigous icl chains. UDC is already much better than UNL in this respect, because it does not limit itself to the first icl, but arrives to the most general category (which in the case of nouns should become ideally volitional_thing, abstract_thing etc., as happens with verbs, that have do, occur or be as a top-level UW in the icl chain). However, in many cases the chain is ambiguous. Take e.g. abet(icl>assist>do): it is not clear if the hypernym is assist>do or assist>work>do, nor it is clear from the links-uw-unl archive: from this point, the original UNL is clearer, since you can check the UCL and look it up in the KB. Ideally, the icl chain should be totally nonambigous, which is of course complex.

The most general problem, I think, is that UNL is still too dependent from WordNet, which provided virtyally all the original UWs. Valency restrictions are an invaluable improvement, but the rest of the database has not grown in the same way. The UDC is of course a great improvement, especially for Russian, and since it has added a number of UWs not existing in English (mostly, I think, cases where Russian has a masculine- and feminine-specific word for profession nouns).

I volunteer to help as much as possible; my special field is Arabic computational linguistics, and I could think about involving some of my collaborators in preparing an Arabic volume. The starting point would be the Arabic WordNet 1.0, which is quite well-down, althouth relatively small, while the Arabic UNL dictionary is poor... и я немного говорю ещё по-русски!

A final desideratum: would it be possible to add a short readme to understand the contents of field 2? I understand it is a project-specific information (I think ETAP-related in the Russian case), but a short legend would be very useful for users.

**Comment by lancioni** [comment]
I'll clone it again: I did it just a few days ago... the true issue, however, is that the last item in an icl chain for a volitional entity should be volitional_thing, otherwise selection restrictions are impossible to enforce.

**Comment by lancioni** [comment]
Actually, I had missed the volitional_thing(icl<thing) entry. Now, things would be much more manageable if entries could be added in links-ext-wn??.csv for all these volitional_thing, abstract_thing... entries. In principle, direct of indirect hyponyms of entity in WN should do.

**Comment by dikonov** [comment]
I am sorry for delayed response, but I was unable to answer earlier. Sometimes I travel and do not read mail. 

>Четверг,  8 июня 2017, 14:48 +03:00 от lancioni <notifications@github.com>:
>
>Thank you for your answer: of course, such matters of design are typically set aside in the earliest stages of a project and become noticeable when it gets hard to correct them. In this specific case, I suspect the difficult thing would be to change the last item in a number of icl chains from thing to volitional_thing (otherwise, having a volitional_thing UW would be pretty useless). This is not that hard actually, because the dictionary has an ontological "backbone". Almost every concept in the resource is linked to the SUMO ontology. The "volitional_thing" concept  corresponds to a sum of "CognitiveAgent", "GroupOfPeople" and "Organization" classes. Thus, every UNL UW linked to any SUMO entities subsumed by these classes can be renamed to have the "icl>volitional_thing" restriction. A quick-and-dirty way to trace such relations is to look into the links-ext-sumo file. Field 4 contains an ontology path, which tells, if the linked SUMO entity and UW are members of some "interesting" class.

Changing the top icl restrictions has been my plan for several years already, but I failed to convince some other people. There are two possible objections now: 1) This would break compatibility with the stale French and Spanish systems. 2) The quality of the links needs to be improved. I am working on the second issue and I already have a new (beta-)version of the UW-SUMO links. It has not been released yet. 

>Another thing that could be improved is having fully nonambigous icl chains. UDC is already much better than UNL in this respect, because it does not limit itself to the first icl, but arrives to the most general category (which in the case of nouns should become ideally volitional_thing, abstract_thing etc., as happens with verbs, that have do, occur or be as a top-level UW in the icl chain). However, in many cases the chain is ambiguous. Take e.g. abet(icl>assist>do): it is not clear if the hypernym is assist>do or assist>work>do, nor it is clear from the links-uw-unl archive: from this point, the original UNL is clearer, since you can check the UCL and look it up in the KB. Ideally, the icl chain should be totally nonambigous, which is of course complex. It is possible to trace most of the icl links between UWs and convert them to unambigous UW-UW links.  I attach an extended UW-links file with 46108 icl relations instead of 3666 in the git version. Please, mind that this data is still incomplete and subject to an update. It can be used as GPL/CC-NC-BY-SA, if you find it useful.  

>The most general problem, I think, is that UNL is still too dependent from WordNet, which provided virtyally all the original UWs. Valency restrictions are an invaluable improvement, but the rest of the database has not grown in the same way. The UDC is of course a great improvement, especially for Russian, and since it has added a number of UWs not existing in English (mostly, I think, cases where Russian has a masculine- and feminine-specific word for profession nouns). I would not call it a dependency. It is simply a matter of available workforce and support. I am perfectly OK with adding any well-defined concepts that lack a Wordnet entry/straight English translation. My favorite examples are   

- be_perceived_as_white(icl>appear>occur,com>white,obj>concrete_thing), be_perceived_as_blue(icl>appear>occur,com>white,obj>concrete_thing)...
- perform_an_action(icl>do,agt>thing,obj>process) (part of a special set of general concepts denoting so-called Lexical Functions) ...
- Russian word "успевать" which has the following senses:
arrive_in_time(icl>occur,obj>thing,tmt>uw,plt>uw)
have_enough_time(icl>be,aoj>volitional_thing,gol>uw)
keep_up_with(icl>perceive>do,equ>follow,agt>person,cag>thing)
keep_up_with(icl>walk>do,equ>pace,agt>living_thing,cag>living_thing)
make_good_progress(icl>advance>do,agt>person,scn>thing) You can also have a look at the terms for family relations like:
 
wife's_mother(icl>mother-in-law>thing,obj>woman,cob>person)
paternal_uncle(icl>uncle>thing,obj>man,cob>person) I know that Arabic has even finer specified words in this field.

>I volunteer to help as much as possible; my special field is Arabic computational linguistics, and I could think about involving some of my collaborators in preparing an Arabic volume. The starting point would be the Arabic WordNet 1.0, which is quite well-down, althouth relatively small, while the Arabic UNL dictionary is poor... и я немного говорю ещё по-русски! This is a great offer and you are welcome! 
I shall add an Arabic volume, if you make it, and I shall try to help in translation of Arabic senses without corresponding English words, if you give a sufficiently good definition.   
I made some experiments in automatic bootstrapping of new languages based on Russian-Vietnamese and Vietnamese-English translation dictionaries. Perhaps, such technique or distributional models could help to extend Arabic data beyond the existing Arabic wordnet. 

>A final desideratum: would it b possible to add a short readme to understand the contents of field 2? I understand it is a project-specific information (I think ETAP-related in the Russian case), but a short legend would be very useful for users. Field 2 in "dict-nl-* " files (natural language <-> UW dictionaries) is system specific. It contains anything that may help to relate the NL word/phrase in field 1 to an entry of some MT system or morphology engine. Russian and English volumes link to ETAP3 "combinatorial dictionaries".  

https://github.com/dikonov/Universal-Dictionary-of-Concepts/blob/master/docs/File%20format%20(ENG).md    explains it.

I added links to to the file format descriptions into the README.md file inside the csv directory.

**Comment by dikonov** [comment]
The top UNL concepts are a very special type of UWs that do not represent conventional word senses. Only some of them could be linked to other semantic resources. The Princeton Wordnet does not have an entry for e.g "volitional thing".
